if (typeof window.ProjectAssembler === 'undefined') {
  window.ProjectAssembler = class ProjectAssembler {

    constructor() {
      this.project = null;
    }

    assemble(fileStructure, options = {}) {
      const {
        projectName = "extracted-project",
        includeReadme = true,
        includeGitignore = true,
        includeDependencies = true,
        treeStructure = null,
        sourceUrl = "",
        timestamp = new Date().toISOString()
      } = options;

      const files = fileStructure.files || [];
      const autoFiles = [];

      if (includeReadme) {
        autoFiles.push(this.generateReadme(projectName, files, treeStructure, sourceUrl, timestamp));
      }

      if (includeGitignore) {
        autoFiles.push(this.generateGitignore(files));
      }

      if (includeDependencies) {
        const depFiles = this.generateDependencyFiles(files);
        autoFiles.push(...depFiles);
      }

      const allFiles = [...files, ...autoFiles];

      this.project = {
        name: projectName,
        sourceUrl,
        timestamp,
        files: allFiles,
        structure: fileStructure,
        autoFiles: autoFiles.length,
        totalSize: allFiles.reduce((sum, f) => sum + (f.size || (f.content ? f.content.length : 0)), 0),
        totalLines: allFiles.reduce((sum, f) => sum + (f.lines !== undefined ? f.lines : (f.content ? f.content.split('\n').length : 0)), 0),
        totalFiles: allFiles.length
      };

      return this.project;
    }

    generateReadme(projectName, files, treeStructure, sourceUrl, timestamp) {
      const tree = treeStructure || this.generateTreeString(files);
      const fileList = files.map((f) => `- \`${f.path || f.fileName}\` (${f.language || "unknown"}, ${f.lines || 0} lines)`).join("\n");

      const languages = {};
      for (const file of files) {
        const lang = file.language || "unknown";
        languages[lang] = (languages[lang] || 0) + 1;
      }
      const langList = Object.entries(languages).map(([lang, count]) => `- ${lang}: ${count} file(s)`).join("\n");

      const content = `# ${projectName}

Generated by Code Extractor & Project Builder

## Project Structure
\`\`\`
${tree}
\`\`\`

## Files
${fileList}

## Languages
${langList}

## Getting Started
Review the extracted files and open in your preferred editor.

---
*Generated on ${new Date(timestamp).toLocaleString()} from ${sourceUrl || "unknown source"}*
`;

      return {
        path: "README.md",
        fileName: "README.md",
        content,
        language: "markdown",
        source: "auto-generated",
        size: content.length,
        lines: content.split("\n").length,
        autoGenerated: true
      };
    }

    generateGitignore(files) {
      const languages = new Set(files.map((f) => f.language));
      let content = `# Auto-generated by Code Extractor

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
.venv/
*.egg-info/
dist/
build/

# Node
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
dist/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
.env.*.local

# Logs
*.log
logs/
`;

      if (languages.has("java")) {
        content += `
# Java
*.class
*.jar
*.war
*.ear
target/
`;
      }

      if (languages.has("csharp") || languages.has("c")) {
        content += `
# C#/C
bin/
obj/
*.exe
*.dll
*.pdb
`;
      }

      return {
        path: ".gitignore",
        fileName: ".gitignore",
        content,
        language: "text",
        source: "auto-generated",
        size: content.length,
        lines: content.split("\n").length,
        autoGenerated: true
      };
    }

    generateDependencyFiles(files) {
      const autoFiles = [];
      const languages = new Set(files.map((f) => f.language));

      if (languages.has("python")) {
        const imports = this.extractPythonImports(files);
        if (imports.length > 0) {
          const content = `# Auto-generated dependencies\n# Review and update versions as needed\n${imports.join("\n")}\n`;
          autoFiles.push({
            path: "requirements.txt",
            fileName: "requirements.txt",
            content,
            language: "text",
            source: "auto-generated",
            size: content.length,
            lines: content.split("\n").length,
            autoGenerated: true
          });
        }
      }

      if (languages.has("javascript") || languages.has("typescript")) {
        const imports = this.extractJsImports(files);
        if (imports.length > 0) {
          const deps = imports.map((imp) => `    "${imp}": "^latest"`).join(",\n");
          const mainFile = files.find((f) => f.language === "javascript" || f.language === "typescript");
          const content = `{
  "name": "extracted-project",
  "version": "1.0.0",
  "description": "Generated by Code Extractor",
  "main": "${mainFile ? mainFile.fileName : "index.js"}",
  "scripts": {
    "start": "node ${mainFile ? mainFile.fileName : "index.js"}",
    "test": "echo \\"Error: no test specified\\" && exit 1"
  },
  "dependencies": {
${deps}
  }
}
`;
          autoFiles.push({
            path: "package.json",
            fileName: "package.json",
            content,
            language: "json",
            source: "auto-generated",
            size: content.length,
            lines: content.split("\n").length,
            autoGenerated: true
          });
        }
      }

      return autoFiles;
    }

    extractPythonImports(files) {
      const imports = new Set();
      const pythonFiles = files.filter((f) => f.language === "python");

      for (const file of pythonFiles) {
        const lines = file.content.split("\n");
        for (const line of lines) {
          const match = line.match(/^(?:import\s+([\w.]+)|from\s+([\w.]+)\s+import)/);
          if (match) {
            const pkg = (match[1] || match[2]).split(".")[0];
            const stdlib = ["os", "sys", "json", "re", "math", "datetime", "collections", "itertools", "functools", "typing", "pathlib", "io", "copy", "time", "random", "string", "textwrap", "logging", "unittest", "argparse"];
            if (!stdlib.includes(pkg)) {
              imports.add(pkg);
            }
          }
        }
      }

      return Array.from(imports).map((imp) => `${imp}`);
    }

    extractJsImports(files) {
      const imports = new Set();
      const jsFiles = files.filter((f) => f.language === "javascript" || f.language === "typescript");

      for (const file of jsFiles) {
        const lines = file.content.split("\n");
        for (const line of lines) {
          const requireMatch = line.match(/require\(['"]([^'"]+)['"]\)/);
          const importMatch = line.match(/from\s+['"]([^'"]+)['"]/);
          const pkg = requireMatch ? requireMatch[1] : importMatch ? importMatch[1] : null;
          if (pkg && !pkg.startsWith(".") && !pkg.startsWith("/")) {
            const packageName = pkg.split("/")[0].startsWith("@") ? pkg.split("/").slice(0, 2).join("/") : pkg.split("/")[0];
            imports.add(packageName);
          }
        }
      }

      return Array.from(imports);
    }

    generateTreeString(files) {
      const tree = {};

      for (const file of files) {
        const path = file.path || file.fileName;
        const parts = path.split("/");
        let current = tree;

        for (let i = 0; i < parts.length; i++) {
          if (!current[parts[i]]) {
            current[parts[i]] = i === parts.length - 1 ? null : {};
          }
          current = current[parts[i]];
        }
      }

      return this.renderTree(tree);
    }

    renderTree(tree, prefix = "", isLast = true, isRoot = true) {
      let result = "";
      const entries = Object.entries(tree);

      for (let i = 0; i < entries.length; i++) {
        const [name, value] = entries[i];
        const connector = i === entries.length - 1 ? "└── " : "├── ";
        const extension = i === entries.length - 1 ? "    " : "│   ";

        if (value === null) {
          result += `${prefix}${connector}${name}\n`;
        } else {
          result += `${prefix}${connector}${name}/\n`;
          result += this.renderTree(value, prefix + extension, i === entries.length - 1, false);
        }
      }

      return result;
    }

    getProject() {
      return this.project;
    }

    getProjectForZip() {
      if (!this.project) return {};

      const zipFiles = {};
      for (const file of this.project.files) {
        zipFiles[file.path || file.fileName] = file.content;
      }
      return zipFiles;
    }

    reset() {
      this.project = null;
    }
  };
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ProjectAssembler: window.ProjectAssembler };
}
