if (typeof window.DependencyGenerator === 'undefined') {
  window.DependencyGenerator = class DependencyGenerator {

    constructor() {
      this.pythonImports = new Set();
      this.nodeModules = new Set();
      this.goModules = new Set();
    }

    generate(project) {
      const result = {
        python: null,
        node: null,
        go: null,
        java: null
      };

      const files = project.files || [];

      const pythonFiles = files.filter(f => f.language === 'python');
      const jsFiles = files.filter(f => f.language === 'javascript' || f.language === 'typescript');
      const goFiles = files.filter(f => f.language === 'go');
      const javaFiles = files.filter(f => f.language === 'java');

      if (pythonFiles.length > 0) {
        result.python = this.generatePythonRequirements(pythonFiles);
      }

      if (jsFiles.length > 0) {
        result.node = this.generatePackageJson(jsFiles, project.name || 'extracted-project');
      }

      if (goFiles.length > 0) {
        result.go = this.generateGoMod(goFiles, project.name || 'extracted-project');
      }

      if (javaFiles.length > 0) {
        result.java = this.generatePomHints(javaFiles);
      }

      return result;
    }

    generatePythonRequirements(files) {
      this.pythonImports.clear();
      const stdlib = new Set([
        'os', 'sys', 'json', 're', 'math', 'datetime', 'collections',
        'itertools', 'functools', 'typing', 'pathlib', 'io', 'copy',
        'time', 'random', 'string', 'textwrap', 'logging', 'unittest',
        'argparse', 'subprocess', 'threading', 'multiprocessing',
        'http', 'urllib', 'email', 'html', 'xml', 'csv', 'hashlib',
        'hmac', 'secrets', 'pickle', 'shelve', 'sqlite3', 'struct',
        'codecs', 'unicodedata', 'difflib', 'enum', 'graphlib',
        'contextlib', 'abc', 'atexit', 'traceback', 'warnings',
        'dataclasses', 'types', 'inspect', 'dis', 'gc', 'pprint',
        'reprlib', 'textwrap', 'wrapcache', 'tempfile', 'glob',
        'shutil', 'fnmatch', 'stat', 'fileinput', 'filecmp',
        'zipfile', 'tarfile', 'gzip', 'bz2', 'lzma', 'zlib',
        'platform', 'errno', 'ctypes', 'signal', 'mmap',
        'asyncio', 'concurrent', 'queue', 'sched', 'select',
        'socket', 'ssl', 'ftplib', 'poplib', 'imaplib', 'smtplib',
        'uuid', 'decimal', 'fractions', 'statistics', 'array',
        'bisect', 'heapq', 'operator', 'itertools'
      ]);

      for (const file of files) {
        const content = file.content || '';
        const lines = content.split('\n');

        for (const line of lines) {
          const trimmed = line.trim();

          const importMatch = trimmed.match(/^import\s+([\w.]+)/);
          if (importMatch) {
            const pkg = importMatch[1].split('.')[0];
            if (!stdlib.has(pkg)) {
              this.pythonImports.add(pkg);
            }
            continue;
          }

          const fromMatch = trimmed.match(/^from\s+([\w.]+)\s+import/);
          if (fromMatch) {
            const pkg = fromMatch[1].split('.')[0];
            if (!stdlib.has(pkg)) {
              this.pythonImports.add(pkg);
            }
          }
        }
      }

      if (this.pythonImports.size === 0) return null;

      let content = '# Auto-generated by Code Extractor\n';
      content += '# Review and update versions as needed\n\n';

      const sortedImports = Array.from(this.pythonImports).sort();
      for (const pkg of sortedImports) {
        content += `${pkg}\n`;
      }

      return content;
    }

    generatePackageJson(files, projectName) {
      this.nodeModules.clear();
      const mainFile = this.findMainFile(files);

      for (const file of files) {
        const content = file.content || '';
        const lines = content.split('\n');

        for (const line of lines) {
          const requireMatch = line.match(/require\s*\(\s*['"]([^'"]+)['"]\s*\)/);
          if (requireMatch) {
            const mod = requireMatch[1];
            if (!mod.startsWith('.') && !mod.startsWith('/')) {
              const pkg = mod.startsWith('@') ? mod.split('/').slice(0, 2).join('/') : mod.split('/')[0];
              this.nodeModules.add(pkg);
            }
            continue;
          }

          const importMatch = line.match(/import\s+.*\s+from\s+['"]([^'"]+)['"]/);
          if (importMatch) {
            const mod = importMatch[1];
            if (!mod.startsWith('.') && !mod.startsWith('/')) {
              const pkg = mod.startsWith('@') ? mod.split('/').slice(0, 2).join('/') : mod.split('/')[0];
              this.nodeModules.add(pkg);
            }
          }
        }
      }

      if (this.nodeModules.size === 0) return null;

      const deps = {};
      const sortedModules = Array.from(this.nodeModules).sort();
      for (const mod of sortedModules) {
        deps[mod] = '^latest';
      }

      const packageJson = {
        name: this.sanitizePackageName(projectName),
        version: '1.0.0',
        description: 'Generated by Code Extractor',
        main: mainFile || 'index.js',
        scripts: {
          start: `node ${mainFile || 'index.js'}`,
          test: 'echo "Error: no test specified" && exit 1'
        },
        dependencies: deps
      };

      return JSON.stringify(packageJson, null, 2) + '\n';
    }

    generateGoMod(files, projectName) {
      this.goModules.clear();
      const moduleName = this.sanitizeModuleName(projectName);

      for (const file of files) {
        const content = file.content || '';
        const lines = content.split('\n');

        for (const line of lines) {
          const trimmed = line.trim();

          if (trimmed.startsWith('import (')) continue;
          if (trimmed === ')') continue;

          const importMatch = trimmed.match(/^"([^"]+)"/);
          if (importMatch) {
            const mod = importMatch[1];
            if (!mod.startsWith('.') && !mod.startsWith('/') && !this.isGoStdlib(mod)) {
              const pkg = mod.split('/')[0];
              this.goModules.add(mod);
            }
          }

          const singleImport = trimmed.match(/^import\s+"([^"]+)"/);
          if (singleImport) {
            const mod = singleImport[1];
            if (!mod.startsWith('.') && !mod.startsWith('/') && !this.isGoStdlib(mod)) {
              this.goModules.add(mod);
            }
          }
        }
      }

      if (this.goModules.size === 0) return null;

      let content = `module ${moduleName}\n\ngo 1.21\n\nrequire (\n`;
      for (const mod of Array.from(this.goModules).sort()) {
        content += `\t${mod} latest\n`;
      }
      content += ')\n';

      return content;
    }

    generatePomHints(files) {
      const hasSpring = files.some(f =>
        (f.content || '').includes('org.springframework') ||
        (f.content || '').includes('@SpringBootApplication') ||
        (f.content || '').includes('@RestController')
      );

      const hasJunit = files.some(f =>
        (f.content || '').includes('org.junit') ||
        (f.content || '').includes('@Test')
      );

      if (!hasSpring && !hasJunit) return null;

      let content = '<!-- Auto-generated by Code Extractor -->\n';
      content += '<!-- Add these dependencies to your pom.xml -->\n\n';
      content += '<dependencies>\n';

      if (hasSpring) {
        content += `  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
  </dependency>\n`;
      }

      if (hasJunit) {
        content += `  <dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter</artifactId>
    <scope>test</scope>
  </dependency>\n`;
      }

      content += '</dependencies>\n';

      return content;
    }

    findMainFile(files) {
      const candidates = ['index.js', 'index.ts', 'main.js', 'main.ts', 'app.js', 'app.ts', 'server.js', 'server.ts'];
      for (const name of candidates) {
        if (files.some(f => (f.name || f.path || '').endsWith(name))) {
          return name;
        }
      }

      const jsFile = files.find(f => f.language === 'javascript' || f.language === 'typescript');
      if (jsFile) return jsFile.name || jsFile.path || 'index.js';

      return 'index.js';
    }

    isGoStdlib(mod) {
      const stdlibPrefixes = [
        'fmt', 'os', 'io', 'net', 'http', 'json', 'strings',
        'strconv', 'errors', 'log', 'time', 'sync', 'context',
        'bufio', 'bytes', 'path', 'regexp', 'sort', 'math',
        'reflect', 'runtime', 'testing', 'flag', 'text',
        'encoding', 'crypto', 'database', 'html', 'mime',
        'archive', 'compress', 'container', 'debug', 'embed',
        'expvar', 'go', 'hash', 'image', 'index', 'internal',
        'maps', 'plugin', 'slices', 'syscall', 'trace', 'unsafe'
      ];
      return stdlibPrefixes.some(prefix => mod === prefix || mod.startsWith(prefix + '/'));
    }

    sanitizePackageName(name) {
      return name
        .toLowerCase()
        .replace(/[^a-z0-9\-_.]/g, '-')
        .replace(/^-+|-+$/g, '')
        .substring(0, 214) || 'extracted-project';
    }

    sanitizeModuleName(name) {
      return 'github.com/user/' + name
        .toLowerCase()
        .replace(/[^a-z0-9\-_.]/g, '-')
        .replace(/^-+|-+$/g, '') || 'github.com/user/extracted-project';
    }
  };
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { DependencyGenerator: window.DependencyGenerator };
}
