if (typeof window.ReadmeGenerator === 'undefined') {
  window.ReadmeGenerator = class ReadmeGenerator {

    constructor() {
      this.treeVisualizer = new TreeVisualizer();
    }

    generate(project) {
      const { name, files, tree, metadata } = project;
      const treeASCII = this.treeVisualizer.toASCII(tree);
      const fileTable = this.generateFileTable(files);
      const languageSection = this.generateLanguageSection(metadata);
      const gettingStarted = this.generateGettingStarted(metadata);

      return `# ${name}

> Auto-generated by Code Extractor Chrome Extension
> Source: ${metadata?.sourceSiteName || 'Unknown'}
> Date: ${metadata?.extractedAt || new Date().toISOString()}

## Project Structure

\`\`\`
${treeASCII}
\`\`\`

## Files Overview

| File | Language | Lines |
|------|----------|-------|
${fileTable}

## Languages Used

${languageSection}

## Getting Started

${gettingStarted}

---
*Source: ${metadata?.sourceURL || 'unknown'} | Extracted: ${metadata?.extractedAt || new Date().toLocaleString()}*
`;
    }

    generateFileTable(files) {
      if (!files || files.length === 0) {
        return '| _No files_ | - | - |';
      }

      return files
        .filter(f => !f.isAutoGenerated)
        .map(f => `| \`${f.path || f.name}\` | ${f.language || 'text'} | ${f.lineCount || f.lines || 0} |`)
        .join('\n');
    }

    generateLanguageSection(metadata) {
      if (!metadata || !metadata.languageBreakdown || Object.keys(metadata.languageBreakdown).length === 0) {
        const languages = metadata?.languages || [];
        if (languages.length === 0) return '- No languages detected';
        return languages.map(lang => `- **${lang}**`).join('\n');
      }

      return Object.entries(metadata.languageBreakdown)
        .map(([lang, stats]) => `- **${lang}**: ${stats.files} files, ${stats.lines} lines`)
        .join('\n');
    }

    generateGettingStarted(metadata) {
      const languages = metadata?.languages || [];
      const sections = [];

      if (languages.includes('python')) {
        sections.push(`### Python Setup
\`\`\`bash
python -m venv venv
source venv/bin/activate  # Linux/Mac
venv\\Scripts\\activate     # Windows
pip install -r requirements.txt
python app.py
\`\`\``);
      }

      if (languages.includes('javascript') || languages.includes('typescript')) {
        sections.push(`### Node.js Setup
\`\`\`bash
npm install
npm start
\`\`\``);
      }

      if (languages.includes('java')) {
        sections.push(`### Java Setup
\`\`\`bash
# Using Maven
mvn clean install
mvn spring-boot:run

# Using Gradle
gradle build
gradle bootRun
\`\`\``);
      }

      if (languages.includes('go')) {
        sections.push(`### Go Setup
\`\`\`bash
go mod download
go run main.go
\`\`\``);
      }

      if (languages.includes('rust')) {
        sections.push(`### Rust Setup
\`\`\`bash
cargo build
cargo run
\`\`\``);
      }

      if (languages.includes('ruby')) {
        sections.push(`### Ruby Setup
\`\`\`bash
bundle install
ruby app.rb
\`\`\``);
      }

      if (languages.includes('php')) {
        sections.push(`### PHP Setup
\`\`\`bash
composer install
php -S localhost:8000
\`\`\``);
      }

      if (sections.length === 0) {
        sections.push(`Open the project files in your preferred editor and review the code.

\`\`\`bash
# If this is a generic project, check individual files for setup instructions
\`\`\``);
      }

      return sections.join('\n\n');
    }

    generateMinimal(project) {
      const { name, files, metadata } = project;
      const treeASCII = this.treeVisualizer.toASCII(project.tree);

      return `# ${name}

Generated by Code Extractor

## Structure
\`\`\`
${treeASCII}
\`\`\`

## Files
${files.map(f => `- \`${f.path || f.name}\` (${f.language || 'text'})`).join('\n')}

---
*Extracted from ${metadata?.sourceURL || 'unknown'}*
`;
    }
  };
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ReadmeGenerator: window.ReadmeGenerator };
}
