if (typeof window.ZipGenerator === 'undefined') {
  window.ZipGenerator = class ZipGenerator {

    constructor(options = {}) {
      this.compressionLevel = options.compressionLevel || 'default';
      this.includeAutoFiles = options.includeAutoFiles !== false;
      this.readmeGenerator = new ReadmeGenerator();
      this.dependencyGenerator = new DependencyGenerator();
      this.treeVisualizer = new TreeVisualizer();
    }

    async generate(project) {
      if (typeof JSZip === 'undefined') {
        throw new Error('JSZip library not loaded');
      }

      const zip = new JSZip();
      const rootName = project.name || 'extracted-project';
      const root = zip.folder(rootName);

      const files = project.files || [];

      for (const file of files) {
        const path = file.path || file.fileName || file.name;
        if (!path) continue;

        const content = file.content || '';
        const parts = path.split('/');

        if (parts.length > 1) {
          let folder = root;
          for (let i = 0; i < parts.length - 1; i++) {
            folder = folder.folder(parts[i]);
          }
          folder.file(parts[parts.length - 1], content);
        } else {
          root.file(path, content);
        }
      }

      if (this.includeAutoFiles) {
        this.addAutoGeneratedFiles(root, project);
      }

      const level = this.compressionLevel === 'high' ? 9 : this.compressionLevel === 'low' ? 1 : 5;

      const blob = await zip.generateAsync({
        type: 'blob',
        compression: 'DEFLATE',
        compressionOptions: { level }
      });

      return {
        blob,
        size: blob.size,
        fileName: `${rootName}.zip`,
        fileCount: files.length
      };
    }

    async generateAndDownload(project) {
      const result = await this.generate(project);

      if (typeof saveAs !== 'undefined') {
        saveAs(result.blob, result.fileName);
      } else {
        const url = URL.createObjectURL(result.blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = result.fileName;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      }

      return result;
    }

    addAutoGeneratedFiles(root, project) {
      const settings = project.settings || {};
      const languages = project.metadata?.languages || project.files?.map(f => f.language).filter(Boolean) || [];

      if (settings.includeReadme !== false) {
        const readme = this.readmeGenerator.generate(project);
        root.file('README.md', readme);
      }

      if (settings.includeGitignore !== false) {
        const gitignore = this.generateGitignore(languages);
        root.file('.gitignore', gitignore);
      }

      if (settings.includeDependencies !== false) {
        const deps = this.dependencyGenerator.generate(project);
        if (deps.python) {
          root.file('requirements.txt', deps.python);
        }
        if (deps.node) {
          root.file('package.json', deps.node);
        }
        if (deps.go) {
          root.file('go.mod', deps.go);
        }
        if (deps.java) {
          root.file('pom-dependencies.xml', deps.java);
        }
      }
    }

    generateGitignore(languages) {
      const templates = {
        python: `# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
.venv/
*.egg-info/
dist/
build/
.eggs/
*.egg
.env
.env.local
*.log
.mypy_cache/
.pytest_cache/
.coverage
htmlcov/
`,
        javascript: `# Node.js
node_modules/
dist/
build/
.next/
.nuxt/
.cache/
coverage/
*.log
npm-debug.log*
.env
.env.local
.env.*.local
.DS_Store
`,
        typescript: `# Node.js
node_modules/
dist/
build/
.next/
.nuxt/
.cache/
coverage/
*.log
npm-debug.log*
.env
.env.local
.env.*.local
.DS_Store
`,
        java: `# Java
*.class
*.jar
*.war
*.ear
target/
.idea/
*.iml
.gradle/
build/
.settings/
.project
.classpath
`,
        go: `# Go
bin/
pkg/
*.exe
*.test
*.out
vendor/
.env
`,
        rust: `# Rust
target/
Cargo.lock
**/*.rs.bk
`,
        ruby: `# Ruby
*.gem
.bundle/
vendor/bundle
log/
tmp/
`,
        php: `# PHP
vendor/
composer.lock
.env
`,
        swift: `# Swift
.DS_Store
*.xcodeproj/
*.xcworkspace/
build/
`,
        csharp: `# C#
bin/
obj/
*.exe
*.dll
*.pdb
*.suo
*.user
`
      };

      let content = `# Auto-generated by Code Extractor
# Combined .gitignore for detected languages

`;

      const uniqueLangs = [...new Set(languages)];
      let hasTemplate = false;

      for (const lang of uniqueLangs) {
        const template = templates[lang];
        if (template) {
          content += template + '\n';
          hasTemplate = true;
        }
      }

      if (!hasTemplate) {
        content += `# Generic
.DS_Store
Thumbs.db
*.log
*.tmp
*.temp
.env
.env.local
.vscode/
.idea/
*.swp
*~
`;
      }

      content += `# OS
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Environment
.env
.env.local
.env.*.local

# Logs
*.log
logs/
`;

      return content;
    }

    async generateFromProject(project) {
      const files = project.files || [];
      return this.generate({
        ...project,
        files,
        name: project.name || 'extracted-project'
      });
    }
  };
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ZipGenerator: window.ZipGenerator };
}
