if (typeof window.TemplateManager === 'undefined') {
  class TemplateManager {
    constructor() {
      this.templates = new Map();
      this.customTemplates = [];
      this._initDefaultTemplates();
    }

    _initDefaultTemplates() {
      this.templates.set('python-web', {
        id: 'python-web',
        name: 'Python Web App',
        description: 'Flask-based web application structure',
        category: 'web',
        language: 'python',
        files: [
          { path: 'app.py', content: 'from flask import Flask\n\napp = Flask(__name__)\n\n@app.route("/")\ndef index():\n    return "Hello, World!"\n\nif __name__ == "__main__":\n    app.run(debug=True)', language: 'python' },
          { path: 'requirements.txt', content: 'flask==3.0.0\npython-dotenv==1.0.0', language: 'text' },
          { path: 'config.py', content: 'import os\n\nclass Config:\n    SECRET_KEY = os.environ.get("SECRET_KEY", "dev-key")\n    DEBUG = True', language: 'python' },
          { path: 'templates/index.html', content: '<!DOCTYPE html>\n<html>\n<head><title>{{ title }}</title></head>\n<body>\n    <h1>Welcome</h1>\n</body>\n</html>', language: 'html' },
          { path: 'static/style.css', content: 'body {\n    font-family: Arial, sans-serif;\n    margin: 0;\n    padding: 20px;\n}', language: 'css' },
          { path: '.gitignore', content: '__pycache__/\n*.pyc\n.env\nvenv/', language: 'text' },
          { path: 'README.md', content: '# Python Web App\n\nGenerated by Code Extractor\n\n## Setup\n```bash\npip install -r requirements.txt\npython app.py\n```', language: 'markdown' }
        ],
        tags: ['flask', 'web', 'python', 'starter']
      });

      this.templates.set('react-app', {
        id: 'react-app',
        name: 'React Application',
        description: 'Basic React app with component structure',
        category: 'web',
        language: 'javascript',
        files: [
          { path: 'src/index.js', content: 'import React from "react";\nimport ReactDOM from "react-dom/client";\nimport App from "./App";\n\nconst root = ReactDOM.createRoot(document.getElementById("root"));\nroot.render(<App />);', language: 'javascript' },
          { path: 'src/App.js', content: 'import React from "react";\n\nfunction App() {\n  return (\n    <div className="App">\n      <h1>React App</h1>\n    </div>\n  );\n}\n\nexport default App;', language: 'javascript' },
          { path: 'src/App.css', content: '.App {\n  text-align: center;\n  padding: 20px;\n}', language: 'css' },
          { path: 'public/index.html', content: '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="utf-8" />\n  <title>React App</title>\n</head>\n<body>\n  <div id="root"></div>\n</body>\n</html>', language: 'html' },
          { path: 'package.json', content: '{\n  "name": "react-app",\n  "version": "1.0.0",\n  "dependencies": {\n    "react": "^18.2.0",\n    "react-dom": "^18.2.0"\n  }\n}', language: 'json' }
        ],
        tags: ['react', 'frontend', 'javascript', 'starter']
      });

      this.templates.set('node-api', {
        id: 'node-api',
        name: 'Node.js REST API',
        description: 'Express-based REST API server',
        category: 'backend',
        language: 'javascript',
        files: [
          { path: 'index.js', content: 'const express = require("express");\nconst app = express();\nconst PORT = process.env.PORT || 3000;\n\napp.use(express.json());\n\napp.get("/", (req, res) => {\n  res.json({ message: "API is running" });\n});\n\napp.listen(PORT, () => {\n  console.log(`Server running on port ${PORT}`);\n});', language: 'javascript' },
          { path: 'package.json', content: '{\n  "name": "node-api",\n  "version": "1.0.0",\n  "main": "index.js",\n  "dependencies": {\n    "express": "^4.18.0"\n  }\n}', language: 'json' },
          { path: '.env', content: 'PORT=3000\nNODE_ENV=development', language: 'text' },
          { path: '.gitignore', content: 'node_modules/\n.env', language: 'text' },
          { path: 'README.md', content: '# Node.js REST API\n\n```bash\nnpm install\nnpm start\n```', language: 'markdown' }
        ],
        tags: ['express', 'api', 'node', 'backend', 'starter']
      });

      this.templates.set('python-data', {
        id: 'python-data',
        name: 'Python Data Science',
        description: 'Data analysis project with Jupyter notebooks',
        category: 'data',
        language: 'python',
        files: [
          { path: 'main.py', content: 'import pandas as pd\nimport numpy as np\n\ndef load_data(filepath):\n    return pd.read_csv(filepath)\n\ndef analyze_data(df):\n    return df.describe()\n\nif __name__ == "__main__":\n    print("Data Science Project")', language: 'python' },
          { path: 'requirements.txt', content: 'pandas==2.1.0\nnumpy==1.24.0\nmatplotlib==3.7.0\njupyter==1.0.0', language: 'text' },
          { path: 'notebooks/analysis.ipynb', content: '{\n "cells": [],\n "metadata": {},\n "nbformat": 4,\n "nbformat_minor": 4\n}', language: 'json' },
          { path: 'data/.gitkeep', content: '', language: 'text' },
          { path: 'README.md', content: '# Data Science Project\n\n```bash\npip install -r requirements.txt\njupyter notebook\n```', language: 'markdown' }
        ],
        tags: ['data', 'pandas', 'python', 'jupyter', 'starter']
      });

      this.templates.set('chrome-extension', {
        id: 'chrome-extension',
        name: 'Chrome Extension',
        description: 'Basic Chrome extension structure',
        category: 'extension',
        language: 'javascript',
        files: [
          { path: 'manifest.json', content: '{\n  "manifest_version": 3,\n  "name": "My Extension",\n  "version": "1.0.0",\n  "action": {\n    "default_popup": "popup.html"\n  },\n  "permissions": ["activeTab"]\n}', language: 'json' },
          { path: 'popup.html', content: '<!DOCTYPE html>\n<html>\n<head><title>Extension</title></head>\n<body>\n  <h1>My Extension</h1>\n  <script src="popup.js"></script>\n</body>\n</html>', language: 'html' },
          { path: 'popup.js', content: 'document.addEventListener("DOMContentLoaded", () => {\n  console.log("Extension loaded");\n});', language: 'javascript' },
          { path: 'background.js', content: 'chrome.runtime.onInstalled.addListener(() => {\n  console.log("Extension installed");\n});', language: 'javascript' }
        ],
        tags: ['chrome', 'extension', 'javascript', 'starter']
      });

      this.templates.set('empty-project', {
        id: 'empty-project',
        name: 'Empty Project',
        description: 'Blank project structure with README',
        category: 'general',
        language: 'text',
        files: [
          { path: 'README.md', content: '# Project\n\nGenerated by Code Extractor', language: 'markdown' },
          { path: '.gitignore', content: '', language: 'text' }
        ],
        tags: ['empty', 'blank', 'starter']
      });
    }

    getTemplate(id) {
      return this.templates.get(id) || this.customTemplates.find(t => t.id === id) || null;
    }

    getAllTemplates() {
      const defaults = Array.from(this.templates.values());
      return [...defaults, ...this.customTemplates];
    }

    getTemplatesByCategory(category) {
      return this.getAllTemplates().filter(t => t.category === category);
    }

    getTemplatesByLanguage(language) {
      return this.getAllTemplates().filter(t => t.language === language.toLowerCase());
    }

    getTemplatesByTag(tag) {
      return this.getAllTemplates().filter(t => t.tags?.includes(tag));
    }

    getCategories() {
      const categories = new Set();
      for (const template of this.getAllTemplates()) {
        if (template.category) categories.add(template.category);
      }
      return Array.from(categories);
    }

    async createProjectFromTemplate(templateId, options = {}) {
      const template = this.getTemplate(templateId);
      if (!template) {
        return { success: false, error: `Template not found: ${templateId}` };
      }

      const projectName = options.projectName || template.name.toLowerCase().replace(/\s+/g, '-');
      const files = template.files.map(file => ({
        ...file,
        content: options.customContent?.[file.path] || file.content,
        source: 'template',
        templateId,
        timestamp: Date.now()
      }));

      return {
        success: true,
        project: {
          name: projectName,
          templateId,
          templateName: template.name,
          files,
          totalFiles: files.length,
          totalLines: files.reduce((sum, f) => sum + (f.content || '').split('\n').length, 0),
          totalSize: files.reduce((sum, f) => sum + (f.content || '').length, 0),
          createdAt: Date.now(),
          source: 'template'
        }
      };
    }

    addCustomTemplate(template) {
      const newTemplate = {
        id: `custom_${Date.now().toString(36)}`,
        name: template.name,
        description: template.description || '',
        category: template.category || 'custom',
        language: template.language || 'text',
        files: template.files || [],
        tags: template.tags || ['custom'],
        isCustom: true,
        createdAt: Date.now(),
        updatedAt: Date.now()
      };

      this.customTemplates.push(newTemplate);
      return newTemplate.id;
    }

    updateCustomTemplate(templateId, updates) {
      const index = this.customTemplates.findIndex(t => t.id === templateId);
      if (index === -1) return false;

      this.customTemplates[index] = {
        ...this.customTemplates[index],
        ...updates,
        updatedAt: Date.now()
      };
      return true;
    }

    deleteCustomTemplate(templateId) {
      const index = this.customTemplates.findIndex(t => t.id === templateId);
      if (index === -1) return false;

      this.customTemplates.splice(index, 1);
      return true;
    }

    exportTemplate(templateId) {
      const template = this.getTemplate(templateId);
      if (!template) return null;

      return {
        version: '1.0.0',
        exportedAt: new Date().toISOString(),
        template
      };
    }

    importTemplate(data) {
      try {
        if (!data.template || !data.template.name || !data.template.files) {
          return { success: false, error: 'Invalid template format' };
        }

        const templateId = this.addCustomTemplate(data.template);
        return { success: true, templateId };
      } catch (error) {
        return { success: false, error: error.message };
      }
    }

    searchTemplates(query) {
      const lowerQuery = query.toLowerCase();
      return this.getAllTemplates().filter(t =>
        t.name.toLowerCase().includes(lowerQuery) ||
        t.description.toLowerCase().includes(lowerQuery) ||
        t.tags?.some(tag => tag.toLowerCase().includes(lowerQuery)) ||
        t.category.toLowerCase().includes(lowerQuery) ||
        t.language.toLowerCase().includes(lowerQuery)
      );
    }

    getTemplateStats() {
      const allTemplates = this.getAllTemplates();
      const categories = {};
      const languages = {};

      for (const t of allTemplates) {
        categories[t.category] = (categories[t.category] || 0) + 1;
        languages[t.language] = (languages[t.language] || 0) + 1;
      }

      return {
        total: allTemplates.length,
        defaults: this.templates.size,
        custom: this.customTemplates.length,
        categories,
        languages
      };
    }
  }

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { TemplateManager };
  }
  window.TemplateManager = TemplateManager;
}
