chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: 'scan-page',
    title: 'Scan Page for Code Blocks',
    contexts: ['page']
  });

  chrome.contextMenus.create({
    id: 'scan-selection',
    title: 'Scan Selected Code',
    contexts: ['selection']
  });

  chrome.contextMenus.create({
    id: 'extract-project',
    title: 'Extract as Project',
    contexts: ['page']
  });

  chrome.contextMenus.create({
    id: 'toggle-live-scan',
    title: 'Toggle Live Scanning',
    contexts: ['page']
  });

  chrome.storage.sync.get(null, (items) => {
    if (Object.keys(items).length === 0) {
      chrome.storage.sync.set({
        theme: 'dark',
        autoScan: false,
        duplicateStrategy: 'latest',
        defaultDownloadFormat: 'zip',
        showNotifications: true,
        highlightCodeBlocks: true,
        includeAutoFiles: true,
        maxHistoryItems: 50,
        compressionLevel: 'default',
        autoGenerateReadme: true,
        autoGenerateDependencies: true,
        liveScan: {
          enabled: true,
          autoStart: true,
          debounceMs: 500,
          showNotifications: true,
          autoAddToProject: true,
          highlightNewBlocks: true,
          maxLiveBlocks: 50,
          pauseOnPopupOpen: false
        },
        versionHistory: {
          enabled: true,
          maxVersionsPerFile: 20,
          autoSave: true
        },
        codeValidation: {
          enabled: true,
          validateOnSave: true,
          validateOnExport: false
        }
      });
    }
  });
});

chrome.contextMenus.onClicked.addListener((info, tab) => {
  if (info.menuItemId === 'scan-page') {
    chrome.tabs.sendMessage(tab.id, { action: 'SCAN_PAGE' });
  } else if (info.menuItemId === 'scan-selection') {
    chrome.tabs.sendMessage(tab.id, { action: 'SCAN_SELECTION' });
  } else if (info.menuItemId === 'extract-project') {
    chrome.tabs.sendMessage(tab.id, { action: 'SCAN_PAGE', data: { extractProject: true } });
  } else if (info.menuItemId === 'toggle-live-scan') {
    chrome.tabs.sendMessage(tab.id, { action: 'TOGGLE_LIVE_SCAN', data: { enabled: true } });
  }
});

const liveScanState = new Map();

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  const { action, data } = message;

  switch (action) {
    case 'SCAN_PAGE':
    case 'SCAN_SELECTION':
      handleScanPage(sender.tab, action === 'SCAN_SELECTION', data, sendResponse);
      return true;

    case 'GENERATE_ZIP':
      handleGenerateZip(data, sendResponse);
      return true;

    case 'DOWNLOAD_FILE':
      handleDownloadFile(data, sendResponse);
      return true;

    case 'SAVE_PROJECT':
      handleSaveProject(data, sendResponse);
      return true;

    case 'GET_PROJECTS':
      handleGetProjects(sendResponse);
      return true;

    case 'GET_PROJECT':
      handleGetProject(data, sendResponse);
      return true;

    case 'DELETE_PROJECT':
      handleDeleteProject(data, sendResponse);
      return true;

    case 'GET_SETTINGS':
      handleGetSettings(sendResponse);
      return true;

    case 'UPDATE_SETTINGS':
      handleUpdateSettings(data, sendResponse);
      return true;

    case 'EXPORT_DATA':
      handleExportData(sendResponse);
      return true;

    case 'IMPORT_DATA':
      handleImportData(data, sendResponse);
      return true;

    case 'OPEN_SIDE_PANEL': {
      const tabId = sender.tab?.id || data?.tabId;
      if (tabId) {
        chrome.sidePanel.open({ tabId });
      }
      sendResponse({ success: true });
      return true;
    }

    case 'LIVE_SCAN_UPDATE':
      handleLiveScanUpdate(data, sender, sendResponse);
      return true;

    case 'MERGE_TABS':
      handleMergeTabs(data, sender, sendResponse);
      return true;

    case 'VERSION_HISTORY_SAVE':
      handleVersionHistorySave(data, sendResponse);
      return true;

    case 'VERSION_HISTORY_GET':
      handleVersionHistoryGet(data, sendResponse);
      return true;

    case 'VERSION_HISTORY_TIMELINE':
      handleVersionHistoryTimeline(data, sendResponse);
      return true;

    case 'VERSION_HISTORY_DIFF':
      handleVersionHistoryDiff(data, sendResponse);
      return true;

    case 'UNIVERSAL_SEARCH':
      handleUniversalSearch(data, sendResponse);
      return true;

    case 'CODE_DIFF':
      handleCodeDiff(data, sendResponse);
      return true;

    case 'IDE_EXPORT':
      handleIDEExport(data, sendResponse);
      return true;

    case 'GITHUB_AUTHENTICATE':
      handleGitHubAuthenticate(data, sendResponse);
      return true;

    case 'GITHUB_GET_REPOS':
      handleGitHubGetRepos(data, sendResponse);
      return true;

    case 'GITHUB_PUSH_PROJECT':
      handleGitHubPushProject(data, sendResponse);
      return true;

    case 'GITHUB_CREATE_GIST':
      handleGitHubCreateGist(data, sendResponse);
      return true;

    case 'TEMPLATE_GET':
      handleTemplateGet(data, sendResponse);
      return true;

    case 'TEMPLATE_CREATE_PROJECT':
      handleTemplateCreateProject(data, sendResponse);
      return true;

    case 'CODE_VALIDATE':
      handleCodeValidate(data, sendResponse);
      return true;

    case 'DUPLICATE_DETECT':
      handleDuplicateDetect(data, sendResponse);
      return true;

    case 'TAB_MANAGER_REGISTER':
      handleTabManagerRegister(data, sender, sendResponse);
      return true;

    case 'AI_REFINE_FILENAMES':
      handleAIRefineFilenames(data, sendResponse);
      return true;

    case 'TEAM_CREATE':
      handleTeamCreate(data, sendResponse);
      return true;

    case 'TEAM_JOIN':
      handleTeamJoin(data, sendResponse);
      return true;

    case 'TEAM_INVITE':
      handleTeamInvite(data, sendResponse);
      return true;

    case 'TEAM_SHARE_PROJECT':
      handleTeamShareProject(data, sendResponse);
      return true;

    case 'TEAM_SYNC_CHANGES':
      handleTeamSyncChanges(data, sender, sendResponse);
      return true;

    case 'CLOUD_SYNC_PUSH':
      handleCloudSyncPush(data, sendResponse);
      return true;

    case 'CLOUD_SYNC_PULL':
      handleCloudSyncPull(data, sendResponse);
      return true;

    case 'CLOUD_SYNC_ALL':
      handleCloudSyncAll(data, sendResponse);
      return true;

    case 'CLOUD_SYNC_STATUS':
      handleCloudSyncStatus(sendResponse);
      return true;

    case 'CUSTOM_PARSER_CREATE':
      handleCustomParserCreate(data, sendResponse);
      return true;

    case 'CUSTOM_PARSER_LIST':
      handleCustomParserList(sendResponse);
      return true;

    case 'CUSTOM_PARSER_DELETE':
      handleCustomParserDelete(data, sendResponse);
      return true;

    case 'API_BRIDGE_ENABLE':
      handleAPIBridgeEnable(data, sendResponse);
      return true;

    case 'API_BRIDGE_DISABLE':
      handleAPIBridgeDisable(sendResponse);
      return true;

    case 'API_BRIDGE_STATUS':
      handleAPIBridgeStatus(sendResponse);
      return true;

    case 'VSCODE_SEND_PROJECT':
      handleVSCodeSendProject(data, sendResponse);
      return true;

    case 'VSCODE_STATUS':
      handleVSCodeStatus(sendResponse);
      return true;

    case 'ANALYTICS_PROJECT':
      handleAnalyticsProject(data, sendResponse);
      return true;

    case 'ANALYTICS_ALL':
      handleAnalyticsAll(sendResponse);
      return true;

    case 'ANALYTICS_HISTORY':
      handleAnalyticsHistory(data, sendResponse);
      return true;

    case 'ANALYTICS_SCORE':
      handleAnalyticsScore(sendResponse);
      return true;

    case 'DEPLOY_VERCEL':
      handleDeployVercel(data, sendResponse);
      return true;

    case 'DEPLOY_NETLIFY':
      handleDeployNetlify(data, sendResponse);
      return true;

    case 'DEPLOY_RAILWAY':
      handleDeployRailway(data, sendResponse);
      return true;

    case 'DEPLOY_GITHUB_PAGES':
      handleDeployGitHubPages(data, sendResponse);
      return true;

    case 'DEPLOY_STATUS':
      handleDeployStatus(sendResponse);
      return true;

    default:
      sendResponse({ error: 'Unknown action' });
      return false;
  }
});

async function handleScanPage(tab, isSelection, data, sendResponse) {
  try {
    const results = await chrome.tabs.sendMessage(tab.id, {
      action: isSelection ? 'SCAN_SELECTION' : 'SCAN_PAGE',
      data: data || {}
    });
    sendResponse({ success: true, data: results });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleGenerateZip(data, sendResponse) {
  try {
    const tab = await chrome.tabs.query({ active: true, currentWindow: true }).then(t => t[0]);
    const result = await chrome.tabs.sendMessage(tab.id, {
      action: 'GENERATE_ZIP',
      data
    });
    sendResponse({ success: true, data: result });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleDownloadFile(data, sendResponse) {
  try {
    const { content, fileName, mimeType = 'application/zip' } = data;
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const downloadId = await chrome.downloads.download({
      url,
      filename: fileName,
      saveAs: true
    });
    sendResponse({ success: true, downloadId });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleSaveProject(data, sendResponse) {
  try {
    const projects = await getStoredProjects();
    const project = {
      id: Date.now().toString(36) + Math.random().toString(36).substr(2, 9),
      ...data,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };
    projects.push(project);
    await chrome.storage.local.set({ projects });
    sendResponse({ success: true, data: project });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleGetProjects(sendResponse) {
  try {
    const projects = await getStoredProjects();
    sendResponse({ success: true, data: projects });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleGetProject(data, sendResponse) {
  try {
    const projects = await getStoredProjects();
    const project = projects.find(p => p.id === data.id);
    if (project) {
      sendResponse({ success: true, data: project });
    } else {
      sendResponse({ success: false, error: 'Project not found' });
    }
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleDeleteProject(data, sendResponse) {
  try {
    let projects = await getStoredProjects();
    projects = projects.filter(p => p.id !== data.id);
    await chrome.storage.local.set({ projects });
    sendResponse({ success: true });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleGetSettings(sendResponse) {
  try {
    const settings = await chrome.storage.sync.get(null);
    sendResponse({ success: true, data: settings });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleUpdateSettings(data, sendResponse) {
  try {
    await chrome.storage.sync.set(data);
    sendResponse({ success: true });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleExportData(sendResponse) {
  try {
    const [localData, syncData] = await Promise.all([
      chrome.storage.local.get(null),
      chrome.storage.sync.get(null)
    ]);
    const exportData = {
      version: '2.0.0',
      exportedAt: new Date().toISOString(),
      local: localData,
      sync: syncData
    };
    sendResponse({ success: true, data: exportData });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleImportData(data, sendResponse) {
  try {
    if (data.local) {
      await chrome.storage.local.set(data.local);
    }
    if (data.sync) {
      await chrome.storage.sync.set(data.sync);
    }
    sendResponse({ success: true });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleLiveScanUpdate(data, sender, sendResponse) {
  try {
    const tabId = sender.tab?.id;
    if (!tabId) {
      sendResponse({ success: false, error: 'No tab ID' });
      return;
    }

    if (!liveScanState.has(tabId)) {
      liveScanState.set(tabId, {
        project: null,
        lastUpdate: null,
        updateCount: 0
      });
    }

    const state = liveScanState.get(tabId);
    state.lastUpdate = data;
    state.updateCount++;

    if (data.project) {
      state.project = data.project;
    }

    chrome.runtime.sendMessage({
      action: 'PROJECT_UPDATED',
      data: {
        tabId,
        addedFiles: data.addedFiles,
        updatedFiles: data.updatedFiles,
        conflicts: data.conflicts,
        summary: data.summary,
        timestamp: data.timestamp
      }
    }).catch(() => { });

    sendResponse({ success: true });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleMergeTabs(data, sender, sendResponse) {
  try {
    const allTabs = await chrome.tabs.query({});
    const projects = [];

    for (const tab of allTabs) {
      try {
        const response = await chrome.tabs.sendMessage(tab.id, {
          action: 'TAB_MANAGER_REQUEST_PROJECT'
        });
        if (response?.success && response.project) {
          projects.push({
            tabId: tab.id,
            url: tab.url,
            title: tab.title,
            project: response.project
          });
        }
      } catch (e) { }
    }

    if (projects.length === 0) {
      sendResponse({ success: false, error: 'No projects found in other tabs' });
      return;
    }

    const mergedFiles = [];
    const fileMap = new Map();

    for (const { project, tabId, url } of projects) {
      for (const file of (project.files || [])) {
        const key = (file.path || file.fileName || '').toLowerCase();
        if (!fileMap.has(key)) {
          fileMap.set(key, { ...file, sourceTabs: [{ tabId, url }] });
          mergedFiles.push(fileMap.get(key));
        } else {
          const existing = fileMap.get(key);
          if ((file.timestamp || 0) > (existing.timestamp || 0)) {
            existing.content = file.content;
            existing.size = file.size;
            existing.lines = file.lines;
          }
          existing.sourceTabs.push({ tabId, url });
        }
      }
    }

    const merged = {
      name: 'merged-project',
      files: mergedFiles,
      totalFiles: mergedFiles.length,
      totalLines: mergedFiles.reduce((sum, f) => sum + (f.lines || 0), 0),
      totalSize: mergedFiles.reduce((sum, f) => sum + (f.size || 0), 0),
      mergedFrom: projects.map(p => ({ tabId: p.tabId, url: p.url, title: p.title })),
      mergedAt: Date.now()
    };

    sendResponse({ success: true, merged, sourceTabs: projects.length });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleVersionHistorySave(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Version history saved (IndexedDB)' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleVersionHistoryGet(data, sendResponse) {
  try {
    sendResponse({ success: true, versions: [] });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleVersionHistoryTimeline(data, sendResponse) {
  try {
    sendResponse({ success: true, timeline: [] });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleVersionHistoryDiff(data, sendResponse) {
  try {
    const oldContent = data.oldContent || '';
    const newContent = data.newContent || '';

    const oldLines = oldContent.split('\n');
    const newLines = newContent.split('\n');
    const diff = [];

    const lcs = computeLCS(oldLines, newLines);
    let i = 0, j = 0, k = 0;

    while (i < oldLines.length || j < newLines.length) {
      if (k < lcs.length && i < oldLines.length && oldLines[i] === lcs[k]) {
        if (j < newLines.length && newLines[j] === lcs[k]) {
          diff.push({ type: 'unchanged', content: newLines[j], lineNum: j + 1 });
          j++; i++; k++;
        } else {
          diff.push({ type: 'removed', content: oldLines[i], lineNum: i + 1 });
          i++;
        }
      } else if (j < newLines.length) {
        diff.push({ type: 'added', content: newLines[j], lineNum: j + 1 });
        j++;
      } else if (i < oldLines.length) {
        diff.push({ type: 'removed', content: oldLines[i], lineNum: i + 1 });
        i++;
      }
    }

    sendResponse({ success: true, diff });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleUniversalSearch(data, sendResponse) {
  try {
    const projects = await getStoredProjects();
    const query = (data.query || '').toLowerCase();
    const results = [];

    for (const project of projects) {
      const name = (project.name || '').toLowerCase();
      const source = (project.sourceUrl || '').toLowerCase();
      if (name.includes(query) || source.includes(query)) {
        results.push(project);
      }
    }

    sendResponse({ success: true, results, total: results.length });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleCodeDiff(data, sendResponse) {
  try {
    const oldContent = data.oldContent || '';
    const newContent = data.newContent || '';

    const oldLines = oldContent.split('\n');
    const newLines = newContent.split('\n');
    const lcs = computeLCS(oldLines, newLines);
    const diff = [];

    let i = 0, j = 0, k = 0;
    while (i < oldLines.length || j < newLines.length) {
      if (k < lcs.length && i < oldLines.length && oldLines[i] === lcs[k]) {
        if (j < newLines.length && newLines[j] === lcs[k]) {
          diff.push({ type: 'unchanged', content: newLines[j], lineNum: j + 1 });
          j++; i++; k++;
        } else {
          diff.push({ type: 'removed', content: oldLines[i], lineNum: i + 1 });
          i++;
        }
      } else if (j < newLines.length) {
        diff.push({ type: 'added', content: newLines[j], lineNum: j + 1 });
        j++;
      } else if (i < oldLines.length) {
        diff.push({ type: 'removed', content: oldLines[i], lineNum: i + 1 });
        i++;
      }
    }

    const additions = diff.filter(l => l.type === 'added').length;
    const deletions = diff.filter(l => l.type === 'removed').length;

    sendResponse({ success: true, diff, stats: { additions, deletions } });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleIDEExport(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'IDE export handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleGitHubAuthenticate(data, sendResponse) {
  try {
    await chrome.storage.sync.set({ 'github.token': data.token });
    sendResponse({ success: true });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleGitHubGetRepos(data, sendResponse) {
  try {
    sendResponse({ success: true, repos: [] });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleGitHubPushProject(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'GitHub push handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleGitHubCreateGist(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'GitHub gist creation handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleTemplateGet(data, sendResponse) {
  try {
    sendResponse({ success: true, templates: [] });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleTemplateCreateProject(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Template project creation handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleCodeValidate(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Code validation handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleDuplicateDetect(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Duplicate detection handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleTabManagerRegister(data, sender, sendResponse) {
  try {
    sendResponse({ success: true });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function getStoredProjects() {
  const result = await chrome.storage.local.get('projects');
  return result.projects || [];
}

function computeLCS(arr1, arr2) {
  const m = arr1.length;
  const n = arr2.length;

  if (m * n > 10000000) {
    const result = [];
    const set2 = new Set(arr2);
    for (const line of arr1) {
      if (set2.has(line)) {
        result.push(line);
        set2.delete(line);
      }
    }
    return result;
  }

  const dp = Array(m + 1).fill(null).map(() => Array(n + 1).fill(0));

  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      if (arr1[i - 1] === arr2[j - 1]) {
        dp[i][j] = dp[i - 1][j - 1] + 1;
      } else {
        dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
      }
    }
  }

  const result = [];
  let i = m, j = n;
  while (i > 0 && j > 0) {
    if (arr1[i - 1] === arr2[j - 1]) {
      result.unshift(arr1[i - 1]);
      i--;
      j--;
    } else if (dp[i - 1][j] > dp[i][j - 1]) {
      i--;
    } else {
      j--;
    }
  }

  return result;
}

chrome.commands.onCommand.addListener(async (command) => {
  if (command === 'scan-page') {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (tab) {
      chrome.tabs.sendMessage(tab.id, { action: 'SCAN_PAGE' });
    }
  } else if (command === '_execute_action') {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (tab) {
      chrome.sidePanel.open({ tabId: tab.id });
    }
  } else if (command === 'toggle-live-scan') {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (tab) {
      chrome.tabs.sendMessage(tab.id, { action: 'TOGGLE_LIVE_SCAN', data: { enabled: true } });
    }
  } else if (command === 'universal-search') {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (tab) {
      chrome.sidePanel.open({ tabId: tab.id });
    }
  } else if (command === 'deploy-project') {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (tab) {
      chrome.sidePanel.open({ tabId: tab.id });
    }
  }
});

async function handleAIRefineFilenames(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'AI filename refinement handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleTeamCreate(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Team creation handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleTeamJoin(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Team join handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleTeamInvite(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Team invite handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleTeamShareProject(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Team project share handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleTeamSyncChanges(data, sender, sendResponse) {
  try {
    chrome.runtime.sendMessage({ action: 'TEAM_CHANGES_RECEIVED', data }).catch(() => {});
    sendResponse({ success: true });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleCloudSyncPush(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Cloud sync push handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleCloudSyncPull(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Cloud sync pull handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleCloudSyncAll(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Cloud sync all handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleCloudSyncStatus(sendResponse) {
  try {
    sendResponse({ success: true, status: 'configured' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleCustomParserCreate(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Custom parser creation handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleCustomParserList(sendResponse) {
  try {
    sendResponse({ success: true, parsers: [] });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleCustomParserDelete(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Custom parser deletion handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleAPIBridgeEnable(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'API bridge enable handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleAPIBridgeDisable(sendResponse) {
  try {
    sendResponse({ success: true, message: 'API bridge disable handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleAPIBridgeStatus(sendResponse) {
  try {
    sendResponse({ success: true, enabled: false });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleVSCodeSendProject(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'VS Code project send handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleVSCodeStatus(sendResponse) {
  try {
    sendResponse({ success: true, connected: false });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleAnalyticsProject(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Project analytics handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleAnalyticsAll(sendResponse) {
  try {
    sendResponse({ success: true, message: 'All projects analytics handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleAnalyticsHistory(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Analytics history handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleAnalyticsScore(sendResponse) {
  try {
    sendResponse({ success: true, message: 'Productivity score handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleDeployVercel(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Vercel deployment handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleDeployNetlify(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Netlify deployment handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleDeployRailway(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'Railway deployment handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleDeployGitHubPages(data, sendResponse) {
  try {
    sendResponse({ success: true, message: 'GitHub Pages deployment handled by content script' });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function handleDeployStatus(sendResponse) {
  try {
    sendResponse({ success: true, deployments: [] });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}
