class TreeView {
  constructor(container, options = {}) {
    this.container = typeof container === 'string' ? document.querySelector(container) : container;
    this.options = {
      showIcons: options.showIcons !== false,
      expandable: options.expandable !== false,
      clickable: options.clickable !== false,
      onFileClick: options.onFileClick || null,
      onDirClick: options.onDirClick || null,
      onContextMenu: options.onContextMenu || null,
      defaultExpanded: options.defaultExpanded !== false
    };
    this.treeData = null;
    this.expandedNodes = new Set();
    this.element = null;
  }

  render(treeData) {
    this.treeData = treeData;
    this.container.innerHTML = '';

    if (!treeData) {
      this.container.innerHTML = '<p class="ce-tree-empty">No tree structure</p>';
      return;
    }

    this.element = document.createElement('div');
    this.element.className = 'ce-tree-view';

    if (this.options.defaultExpanded) {
      this.expandAll(treeData);
    }

    this.element.appendChild(this.buildNode(treeData, 0, true));
    this.container.appendChild(this.element);
  }

  buildNode(node, depth, isLast) {
    const wrapper = document.createElement('div');
    wrapper.className = 'ce-tree-node';
    wrapper.dataset.depth = depth;
    wrapper.dataset.name = node.name || '';
    wrapper.dataset.path = node.path || node.name || '';

    const isDir = node.type === 'directory' || (node.children && node.children.length > 0);
    const isExpanded = this.expandedNodes.has(node.path || node.name);

    const row = document.createElement('div');
    row.className = 'ce-tree-row';

    const indent = document.createElement('span');
    indent.className = 'ce-tree-indent';
    for (let i = 0; i < depth; i++) {
      indent.innerHTML += '<span class="ce-tree-indent-line"></span>';
    }
    row.appendChild(indent);

    const connector = document.createElement('span');
    connector.className = 'ce-tree-connector';
    connector.textContent = isLast ? '└── ' : '├── ';
    row.appendChild(connector);

    if (this.options.showIcons) {
      const icon = document.createElement('span');
      icon.className = 'ce-tree-icon';
      icon.textContent = isDir ? (isExpanded ? '📂' : '📁') : this.getFileIcon(node.name);
      row.appendChild(icon);
    }

    if (isDir && this.options.expandable) {
      const toggle = document.createElement('span');
      toggle.className = 'ce-tree-toggle';
      toggle.textContent = isExpanded ? '▾' : '▸';
      toggle.addEventListener('click', (e) => {
        e.stopPropagation();
        this.toggleNode(node);
      });
      row.insertBefore(toggle, row.lastChild);
    }

    const nameEl = document.createElement('span');
    nameEl.className = 'ce-tree-name' + (isDir ? ' ce-tree-name-dir' : '');
    nameEl.textContent = node.name || '';

    if (this.options.clickable && !isDir) {
      nameEl.classList.add('ce-tree-name-clickable');
      nameEl.addEventListener('click', () => {
        if (this.options.onFileClick) {
          this.options.onFileClick(node);
        }
      });
    }

    if (isDir && this.options.onDirClick) {
      nameEl.classList.add('ce-tree-name-dir-clickable');
      nameEl.addEventListener('click', () => {
        this.options.onDirClick(node);
      });
    }

    row.appendChild(nameEl);

    if (node.codeBlockId) {
      const check = document.createElement('span');
      check.className = 'ce-tree-check';
      check.textContent = '✅';
      row.appendChild(check);
    }

    if (node.isAutoGenerated) {
      const auto = document.createElement('span');
      auto.className = 'ce-tree-auto';
      auto.textContent = '⚡';
      row.appendChild(auto);
    }

    wrapper.appendChild(row);

    if (isDir && node.children && node.children.length > 0 && isExpanded) {
      const childContainer = document.createElement('div');
      childContainer.className = 'ce-tree-children';

      for (let i = 0; i < node.children.length; i++) {
        const child = node.children[i];
        childContainer.appendChild(this.buildNode(child, depth + 1, i === node.children.length - 1));
      }

      wrapper.appendChild(childContainer);
    }

    if (this.options.onContextMenu) {
      row.addEventListener('contextmenu', (e) => {
        e.preventDefault();
        this.options.onContextMenu(node, e);
      });
    }

    return wrapper;
  }

  toggleNode(node) {
    const key = node.path || node.name;
    if (this.expandedNodes.has(key)) {
      this.expandedNodes.delete(key);
    } else {
      this.expandedNodes.add(key);
    }
    this.render(this.treeData);
  }

  expandAll(node) {
    if (!node) return;
    const key = node.path || node.name;
    this.expandedNodes.add(key);
    if (node.children) {
      for (const child of node.children) {
        this.expandAll(child);
      }
    }
  }

  collapseAll(node) {
    if (!node) return;
    const key = node.path || node.name;
    this.expandedNodes.delete(key);
    if (node.children) {
      for (const child of node.children) {
        this.collapseAll(child);
      }
    }
  }

  expandToNode(path) {
    const parts = path.split('/');
    let current = '';
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      this.expandedNodes.add(current);
    }
    this.render(this.treeData);
  }

  highlightNode(path) {
    if (!this.element) return;
    const nodes = this.element.querySelectorAll('.ce-tree-node');
    nodes.forEach(n => n.classList.remove('ce-tree-node-highlighted'));

    const target = this.element.querySelector(`[data-path="${path}"]`);
    if (target) {
      target.classList.add('ce-tree-node-highlighted');
      target.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
  }

  getFileIcon(fileName) {
    if (!fileName) return '📄';
    const ext = '.' + fileName.split('.').pop().toLowerCase();
    const baseName = fileName.split('/').pop().toLowerCase();

    const specialIcons = {
      'dockerfile': '🐳',
      'makefile': '🔧',
      'jenkinsfile': '🔧',
      'license': '📜',
      'readme': '📝',
      '.gitignore': '🔒',
      '.env': '🔐'
    };

    if (specialIcons[baseName]) return specialIcons[baseName];

    const extIcons = {
      '.py': '🐍', '.js': '📜', '.ts': '📘', '.tsx': '⚛️', '.jsx': '⚛️',
      '.html': '🌐', '.css': '🎨', '.scss': '🎨', '.json': '📋',
      '.yml': '⚙️', '.yaml': '⚙️', '.xml': '📄', '.md': '📝',
      '.sql': '🗃️', '.sh': '💻', '.java': '☕', '.go': '🔷',
      '.rs': '🦀', '.rb': '💎', '.php': '🐘', '.swift': '🐦',
      '.kt': '🔮', '.vue': '💚', '.svelte': '🔥', '.txt': '📄'
    };

    return extIcons[ext] || '📄';
  }

  getSelectedNode() {
    if (!this.element) return null;
    const selected = this.element.querySelector('.ce-tree-node-selected');
    if (!selected) return null;
    return {
      name: selected.dataset.name,
      path: selected.dataset.path,
      depth: parseInt(selected.dataset.depth)
    };
  }

  clear() {
    this.treeData = null;
    this.expandedNodes.clear();
    this.element = null;
    this.container.innerHTML = '';
  }
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { TreeView };
}
